version: '3.1'

services:

  db:
    image: postgres
    environment:
      POSTGRES_USER: snapshot
      POSTGRES_PASSWORD: snapshot
      POSTGRES_DB: snapshot
    volumes:
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"